name: Update Calendar

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate calendar
        run: python generate_calendar.py
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}

      - name: Commit update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.ics
          git commit -m "calendar update" || exit 0
          git push
